<?php
session_start();

// --- 1. CONFIGURATION ---
// Connect directly to the SQLite database generated by the python scripts
$sqlite_db = '../largeDB.db';

// SHA-256 hash for the password "admin123"
$hardcoded_hash = '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9';

// --- 2. AUTHENTICATION LOGIC ---
$login_error = false;

// Handle login form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['password'])) {
    if (hash('sha256', $_POST['password']) === $hardcoded_hash) {
        $_SESSION['authenticated'] = true;
        // Redirect to avoid form resubmission on refresh
        header("Location: " . $_SERVER['PHP_SELF']); 
        exit;
    } else {
        $login_error = true;
    }
}

// --- 3. API ENDPOINTS (Returns JSON to the map) ---
// If the user requests data but isn't logged in, block them.
if (isset($_GET['action'])) {
    header('Content-Type: application/json');
    
    if (empty($_SESSION['authenticated'])) {
        http_response_code(401);
        echo json_encode(['error' => 'Unauthorized']);
        exit;
    }

    try {
        $pdo = new PDO("sqlite:" . $sqlite_db);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        if ($_GET['action'] === 'get_tags') {
            $stmt = $pdo->query("SELECT name, hashed_key FROM tags");
            echo json_encode($stmt->fetchAll(PDO::FETCH_ASSOC));
            exit;
        }

        if ($_GET['action'] === 'get_locations' && isset($_GET['key'])) {
            // Query the trips table with all its new calculated columns
            $stmt = $pdo->prepare("SELECT latitude, longitude, time, velocity, distance, motion_state, time_spent, transport_mode, elevation FROM trips WHERE hashed_key = ? ORDER BY time ASC");
            $stmt->execute([$_GET['key']]);
            echo json_encode($stmt->fetchAll(PDO::FETCH_ASSOC));
            exit;
        }

        if ($_GET['action'] === 'get_places') {
            $stmt = $pdo->query("SELECT latitude, longitude, significance, unique_tags, is_overnight FROM places");
            echo json_encode($stmt->fetchAll(PDO::FETCH_ASSOC));
            exit;
        }
    } catch (PDOException $e) {
        http_response_code(500);
        echo json_encode(['error' => $e->getMessage()]);
        exit;
    }
}

// --- 4. HTML FRONTEND (Served only if authenticated) ---
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trips Viewer</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <style>
        body, html { margin: 0; padding: 0; height: 100%; font-family: sans-serif; background: #f4f4f4; }
        
        /* Login Screen */
        .login-wrapper {
            display: flex; flex-direction: column; align-items: center; justify-content: center;
            height: 100vh; background: #2c3e50; color: white;
        }
        .login-wrapper input { padding: 10px; margin: 10px 0; width: 200px; border-radius: 4px; border: none; }
        .login-wrapper button { padding: 10px 20px; cursor: pointer; background: #3498db; border: none; color: white; border-radius: 4px;}
        
        /* Main App Screen */
        #app-screen { display: flex; height: 100vh; flex-direction: column; }
        #top-bar { padding: 15px; background: #fff; box-shadow: 0 2px 4px rgba(0,0,0,0.1); z-index: 1000; display: flex; align-items: center; gap: 15px; flex-wrap: wrap; }
        #top-bar select { padding: 8px; font-size: 16px; border-radius: 4px; }
        #map { flex-grow: 1; width: 100%; }
        
        /* Legend */
        .legend { font-size: 14px; display: flex; align-items: center; gap: 15px; margin-left: auto; }
        .legend-item { display: flex; align-items: center; gap: 5px; }
        .color-box { width: 14px; height: 14px; border-radius: 3px; }
    </style>
</head>
<body>

<?php if (empty($_SESSION['authenticated'])): ?>
    <div class="login-wrapper">
        <h2>Trips Dashboard</h2>
        <form method="POST">
            <input type="password" name="password" placeholder="Enter password" required />
            <br>
            <button type="submit">Login</button>
        </form>
        <?php if ($login_error): ?>
            <p style="color: #e74c3c;">Incorrect Password</p>
        <?php endif; ?>
    </div>
<?php else: ?>
    <div id="app-screen">
        <div id="top-bar">

            <label for="view-mode"><strong>View Mode:</strong></label>
            <select id="view-mode" onchange="toggleViewMode()" style="margin-right: 20px;">
                <option value="trips" selected>Trips</option>
                <option value="places">Places</option>
            </select>
            <label for="tag-select"><strong>Select Tracker:</strong></label>
            <select id="tag-select" onchange="loadMapData()">
                <option value="" disabled selected>Loading tags...</option>
            </select>
            
            <label for="time-scale" style="margin-left: 20px;"><strong>Time Scale:</strong></label>
            <select id="time-scale" onchange="handleTimeScaleChange()">
                <option value="24h">Last 24 Hours</option>
                <option value="7d">Last 7 Days</option>
                <option value="30d">Last 30 Days</option>
                <option value="all" selected>All Time</option>
                <option value="custom">Custom Range</option>
                <option value="day">Single Day</option>
            </select>

            <div id="custom-date-range" style="display: none; align-items: center; gap: 5px; margin-left: 10px;">
                <input type="datetime-local" id="start-date" onchange="loadMapData()" style="padding: 6px; font-size: 14px; border-radius: 4px; border: 1px solid #ccc;">
                <span>to</span>
                <input type="datetime-local" id="end-date" onchange="loadMapData()" style="padding: 6px; font-size: 14px; border-radius: 4px; border: 1px solid #ccc;">
            </div>

            <div id="single-day-controls" style="display: none; align-items: center; gap: 5px; margin-left: 10px;">
                <button id="prev-day-btn" onclick="changeDay(-1)" style="padding: 6px; cursor: pointer; border-radius: 4px; border: 1px solid #ccc; background: #fff;">&#8592; Prev</button>
                <input type="date" id="single-date" onchange="loadMapData()" style="padding: 6px; font-size: 14px; border-radius: 4px; border: 1px solid #ccc;">
                <button id="next-day-btn" onclick="changeDay(1)" style="padding: 6px; cursor: pointer; border-radius: 4px; border: 1px solid #ccc; background: #fff;">Next &#8594;</button>
            </div>

            <label id="significance-label" for="significance-input" style="margin-left: 20px; display: none;"><strong>Min Significance:</strong></label>
            <input type="number" id="significance-input" value="0" min="0" step="1" onchange="loadPlacesData()" style="display: none; width: 80px; padding: 8px; font-size: 16px; border-radius: 4px; border: 1px solid #ccc;">
            <select id="significance-unit" onchange="loadPlacesData()" style="display: none; margin-left: 5px;">
                <option value="minutes" selected>Minutes</option>
                <option value="hours">Hours</option>
            </select>
            
            <div id="legend-trips" class="legend">
                <div class="legend-item"><div class="color-box" style="background: gray;"></div> Stationary</div>
                <div class="legend-item"><div class="color-box" style="background: #27ae60;"></div> Walking</div>
                <div class="legend-item"><div class="color-box" style="background: #2980b9;"></div> Cycling/Running</div>
                <div class="legend-item"><div class="color-box" style="background: #c0392b;"></div> Driving/Train</div>
                <div class="legend-item"><div class="color-box" style="background: #f39c12;"></div> Unknown / Init</div>
            </div>
            
            <div id="legend-places" class="legend" style="display: none;">
                <div class="legend-item"><div class="color-box" style="background: #8e44ad; border-radius: 50%;"></div> Places (Size based on significance)</div>
                <div class="legend-item"><div class="color-box" style="background: #e67e22; border-radius: 50%;"></div> Overnight Places</div>
            </div>
        </div>
        <div id="map"></div>
    </div>

    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script>
        let map;
        let mapLayers = []; 

        document.addEventListener('DOMContentLoaded', () => {
            map = L.map('map').setView([48.1486, 17.1077], 13);
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '© OpenStreetMap'
            }).addTo(map);

            fetchTags();
        });

        async function fetchTags() {
            try {
                const response = await fetch('?action=get_tags');
                const tags = await response.json();
                
                const select = document.getElementById('tag-select');
                select.innerHTML = '<option value="" disabled selected>Select a tracker...</option>';
                
                tags.forEach(tag => {
                    const option = document.createElement('option');
                    option.value = tag.hashed_key;
                    option.textContent = tag.name;
                    select.appendChild(option);
                });
            } catch (err) {
                console.error("Error fetching tags:", err);
            }
        }

        function toggleViewMode() {
            const mode = document.getElementById('view-mode').value;
            if (mode === 'trips') {
                document.getElementById('tag-select').disabled = false;
                document.getElementById('time-scale').disabled = false;
                document.getElementById('start-date').disabled = false;
                document.getElementById('end-date').disabled = false;
                document.getElementById('single-date').disabled = false;
                document.getElementById('prev-day-btn').disabled = false;
                document.getElementById('next-day-btn').disabled = false;
                document.getElementById('legend-trips').style.display = 'flex';
                document.getElementById('legend-places').style.display = 'none';
                document.getElementById('significance-label').style.display = 'none';
                document.getElementById('significance-input').style.display = 'none';
                document.getElementById('significance-unit').style.display = 'none';
                loadMapData();
            } else {
                document.getElementById('tag-select').disabled = true;
                document.getElementById('time-scale').disabled = true;
                document.getElementById('start-date').disabled = true;
                document.getElementById('end-date').disabled = true;
                document.getElementById('single-date').disabled = true;
                document.getElementById('prev-day-btn').disabled = true;
                document.getElementById('next-day-btn').disabled = true;
                document.getElementById('legend-trips').style.display = 'none';
                document.getElementById('legend-places').style.display = 'flex';
                document.getElementById('significance-label').style.display = 'inline';
                document.getElementById('significance-input').style.display = 'inline';
                document.getElementById('significance-unit').style.display = 'inline';
                loadPlacesData();
            }
        }

        function handleTimeScaleChange() {
            const timeScale = document.getElementById('time-scale').value;
            const customRangeDiv = document.getElementById('custom-date-range');
            const singleDayDiv = document.getElementById('single-day-controls');

            if (timeScale === 'custom') {
                customRangeDiv.style.display = 'flex';
            } else {
                customRangeDiv.style.display = 'none';
            }

            if (timeScale === 'day') {
                singleDayDiv.style.display = 'flex';
                if (!document.getElementById('single-date').value) {
                    document.getElementById('single-date').value = new Date().toISOString().split('T')[0];
                }
            } else {
                singleDayDiv.style.display = 'none';
            }

            loadMapData();
        }

        function changeDay(offset) {
            const dateInput = document.getElementById('single-date');
            if (!dateInput.value) {
                dateInput.value = new Date().toISOString().split('T')[0];
            }
            
            const parts = dateInput.value.split('-');
            const d = new Date(parts[0], parts[1] - 1, parts[2]);
            d.setDate(d.getDate() + offset);
            
            const yyyy = d.getFullYear();
            const mm = String(d.getMonth() + 1).padStart(2, '0');
            const dd = String(d.getDate()).padStart(2, '0');
            dateInput.value = `${yyyy}-${mm}-${dd}`;
            
            loadMapData();
        }

        async function loadMapData() {
            const tagKey = document.getElementById('tag-select').value;
            const timeScale = document.getElementById('time-scale').value;
            if (!tagKey) return;

            try {
                const response = await fetch(`?action=get_locations&key=${encodeURIComponent(tagKey)}`);
                const allLocations = await response.json();
                
                const filteredLocations = filterByTimeScale(allLocations, timeScale);
                drawLocations(filteredLocations);
            } catch (err) {
                console.error("Error fetching locations:", err);
            }
        }

        async function loadPlacesData() {
            try {
                const response = await fetch(`?action=get_places`);
                const places = await response.json();
                drawPlaces(places);
            } catch (err) {
                console.error("Error fetching places:", err);
            }
        }

        function filterByTimeScale(locations, timeScale) {
            const now = new Date();
            let startDate = null;
            let endDate = null;

            switch (timeScale) {
                case '24h': startDate = new Date(now.getTime() - 24 * 60 * 60 * 1000); break;
                case '7d': startDate = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000); break;
                case '30d': startDate = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000); break;
                case 'custom':
                    const startInput = document.getElementById('start-date').value;
                    const endInput = document.getElementById('end-date').value;
                    if (startInput) startDate = new Date(startInput);
                    if (endInput) endDate = new Date(endInput);
                    break;
                case 'day':
                    const singleDateVal = document.getElementById('single-date').value;
                    if (singleDateVal) {
                        return locations.filter(loc => loc.time.startsWith(singleDateVal));
                    }
                    break;
                case 'all': default: return locations;
            }
            return locations.filter(loc => {
                const locDate = new Date(loc.time);
                if (startDate && locDate < startDate) return false;
                if (endDate && locDate > endDate) return false;
                return true;
            });
        }

        function getModeColor(mode) {
            switch (mode) {
                case 'STATIONARY': return 'gray';
                case 'WALKING': return '#27ae60';
                case 'RUNNING/CYCLING': return '#2980b9';
                case 'DRIVING/TRAIN': return '#c0392b';
                default: return '#f39c12'; // UNKNOWN or INIT
            }
        }

        function drawLocations(locations) {
            mapLayers.forEach(layer => map.removeLayer(layer));
            mapLayers = [];

            if (locations.length === 0) {
                // alert("No trips found for this tracker in the selected time period.");
                return;
            }

            const latLngs = [];

            for (let i = 0; i < locations.length; i++) {
                const loc = locations[i];
                const color = getModeColor(loc.transport_mode);
                const currentPoint = [loc.latitude, loc.longitude];
                latLngs.push(currentPoint);

                // Draw connecting line (Colored by the mode of the segment arriving at this point)
                if (i > 0) {
                    const prevPoint = [locations[i-1].latitude, locations[i-1].longitude];
                    
                    let polylineOptions = { color: color, weight: 4, opacity: 0.8 };
                    if (loc.motion_state === 'INIT') {
                        polylineOptions.dashArray = '10, 10';
                    }
                    
                    const polyline = L.polyline([prevPoint, currentPoint], polylineOptions).addTo(map);
                    mapLayers.push(polyline);
                }

                // Visible GPS Dot
                const circle = L.circleMarker(currentPoint, { radius: (loc.motion_state === 'STATIONARY' ? 9 : 6), fillColor: color, color: '#fff', weight: 1, fillOpacity: 0.9 }).addTo(map);
                
                const velocity = loc.velocity !== null ? parseFloat(loc.velocity).toFixed(2) + ' km/h' : 'N/A';
                const distance = loc.distance !== null ? parseFloat(loc.distance).toFixed(2) + ' m' : 'N/A';
                const timeSpent = loc.time_spent !== null ? parseFloat(loc.time_spent/60).toFixed(2) + ' hours' : 'N/A';
                const elevation = loc.elevation !== null ? parseFloat(loc.elevation).toFixed(2) + ' m' : 'N/A';


                // Invisible larger clickable area for tooltips
                const invisibleCircle = L.circleMarker(currentPoint, { radius: 25, fillColor: 'transparent', color: 'transparent', weight: 0, fillOpacity: 0 })
                    .bindPopup(`Time: ${loc.time}<br>State: <b>${loc.motion_state}</b><br>Mode: <b>${loc.transport_mode}</b><br>Velocity: ${velocity}<br>Distance: ${distance}<br>Time Spent: ${timeSpent}<br>Elevation: ${elevation}`).addTo(map);
                
                mapLayers.push(invisibleCircle);
                mapLayers.push(circle);
            }

            const bounds = L.latLngBounds(latLngs);
            map.fitBounds(bounds, { padding: [50, 50] });
        }

        function drawPlaces(places) {
            mapLayers.forEach(layer => map.removeLayer(layer));
            mapLayers = [];

            const minSigInput = parseFloat(document.getElementById('significance-input').value) || 0;
            const unit = document.getElementById('significance-unit').value;
            const minSignificance = unit === 'hours' ? minSigInput * 60 : minSigInput;

            const filteredPlaces = places.filter(p => parseFloat(p.significance) >= minSignificance);

            if (filteredPlaces.length === 0) {
                alert("No places found matching the criteria.");
                return;
            }

            const latLngs = [];

            filteredPlaces.forEach(place => {
                const currentPoint = [place.latitude, place.longitude];
                latLngs.push(currentPoint);

                const sig = parseFloat(place.significance) || 0;
                // Scale size logarithmically to keep it visible but not overwhelming
                const radius = Math.min(Math.max(8, Math.log(sig + 1) * 4), 60);

                let displaySig = sig;
                let displayUnit = "min";
                if (unit === 'hours') {
                    displaySig = sig / 60;
                    displayUnit = "hours";
                }

                const isOvernight = (place.is_overnight == 1 || place.is_overnight === 'true' || place.is_overnight === true);
                const fillColor = isOvernight ? '#e67e22' : '#8e44ad';

                const circle = L.circleMarker(currentPoint, { radius: radius, fillColor: fillColor, color: '#fff', weight: 1, fillOpacity: 0.6 })
                    .bindPopup(`<b>Popular Place</b><br>Time Spent: ${displaySig.toFixed(2)} ${displayUnit}<br>Unique Trackers: ${place.unique_tags}<br>Overnight: ${isOvernight ? 'Yes' : 'No'}`).addTo(map);
                
                mapLayers.push(circle);
            });

            const bounds = L.latLngBounds(latLngs);
            map.fitBounds(bounds, { padding: [50, 50] });
        }
    </script>
<?php endif; ?>
</body>
</html>